/*
 * Copyright (c) 2009-2011 Daniel Oom, see license.txt for more info.
 */

package game.components;

public enum ComponentType {
  HEALTH, GRAPHIC, GRAVITY, INFO_BAR, SPAWNER, INVENTORY, CONTROL, HAND, WEAPON,
  MOVING_COLLISION, RANGE_LIMITER, ACTION_ON_DEATH, MOVEMENT, MOVEMENT_CONSTRAINTS,
  PROJECTILE_DAMAGE, LINE_TO_ORIGIN, EFFECT_ON_ANIMATION_FRAME, STATIC_COLLISION
}
