{ player1:
  { walkUp: "W"
  , walkDown: "S"
  , walkLeft: "A"
  , walkRight: "D"
  , fire: "SPACE"
  , nextWeapon: "E"
  , previousWeapon: "Q"
  , buy: "F"
  , weapon0: "1"
  , weapon1: "2"
  , weapon2: "3"
  , weapon3: "4"
  , weapon4: "5" }
, player2:
  { walkUp: "I"
  , walkDown: "K"
  , walkLeft: "H"
  , walkRight: "L"
  , fire: "RETURN"
  , nextWeapon: "P"
  , previousWeapon: "U"
  , buy: "BACK"
  , weapon0: "6"
  , weapon1: "7"
  , weapon2: "8"
  , weapon3: "9"
  , weapon4: "0" } }
